spring:
  datasource:

    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/water
    password: root
    username: my_secret_password
  application:
    name: water-service
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8086
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${instanceId:${random.value}}