spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/teza
    driverClassName: com.mysql.cj.jdbc.Driver
    password: root
  application:
    name: counter-service
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${instanceId:${random.value}}